### ISSUE TITLE
SVG Preflight Checklist

### ISSUE THREAD

**Issue by g-a-v-i-n** [bumblebee-systems/bibos#49]
Ensure animated traits can reverse on the following
- [x] Face
- [x] body circles
- [x] hovering glints
- [x] mote rotation
- [x] mote floating

**Token**
- [x] Token description

**Misc**
- [x] ensure cross-browser + rainbow compatibility with `rrggbbaa` hex code format. All modern browsers do.
- [x] Ensure all reasonable renders support SVG2 - `xlink:href` is deprecated in SVG2, so we use `href`
- [x] Potentially include the background color in attributes to make bibo viewer easier to build. Otherwise will have to grab that color from the SVG. Would need to include an `id` property on the tag.
- [x] filters, paths etc with an `id` should be unique to bibos because id properties are global for any given html doc. Since these are uniform across all bibos, we don't need to namespace these to each bibo.
